algoritmo "Repetição 3 - para"

var
    cont: inteiro

inicio
//Estrutura BÁSICA de repetição PARA
        // para i de inicial ate final passo k faca
            // escreval (i)
        // fimpara

        para cont <- 1 ate 10 faca
            escreval(cont)
        fimpara

//Pulando de 2 em 2 números na contagem ao colocar o incremento passo 2
        para cont <- 1 ate 10 passo 2 faca
            escreval(cont)
        fimpara

fimalgoritmo