algoritmo "Loop infinito"

var
    cont: inteiro

inicio

        cont <- 0
//neste exemplo a estrutura de repetição não executa uma operação para somar um valor com a variável cont para aumentar seu valor e sair do loop, assim ela sempre será zero e menor do que 1, dessa maneira o programa entra em loop infinito, até que o programa seja parado manualmente.

        enquanto(cont < 1) faca
            escreva(cont)
        fimenquanto

fimalgoritmo