algoritmo "Atividade 40"
// Descrição : Programa que faz uma contagem de 3 em 3 números iniciando do 0 até o 18 exibindo os números (0, 3, 6, 9, 12, 15, 18).

var
    cont: inteiro

inicio
//Entrada de dados
        cont <- 0

//Estrutura de repetição enquanto
        enquanto (cont <= 18) faca
            escreval(cont)
            cont <- cont + 3
        fimenquanto

        escreval("Acabou.")

fimalgoritmo