algoritmo "Comandos de saída"

var
// As variáveis possuem diferentes tipos e cada tipo armazena um valor diferente.
// Inteiro    :   1   3   -5  198  0
// Real       :   0.5    5.0    9.8   -77.3   3.1415
// Caractere  :   "Gabriel"     "Algoritmo"     "123%&"
// Logico     :   verdadeiro    falso
   msg: caractere

inicio
    msg <- "Gabriel"

    escreval("Olá mundo")
    escreval("msg")
    escreval(msg)
    escreval("mensagem ", msg)

fimalgoritmo